config/routes.rb
GoodShepherd::Application.routes.draw do
  #comment
  resources :events
  resources :churches do
    get :members, :on => :member
    resources :weekly_meetings
    resources :meetings do
      resources :attendances, :only => [:create]
    end
    get 'upload_directory', :on => :member
    post 'upload_directory', :on => :member    
  end
  
  match '/weekly_calendar' => 'churches#calendar', :as => :weekly_calendar
  match '/weekly_calendar/meetings' => 'churches#calendar_meetings', :as => :weekly_calendar_meetings

  match '/meetings/:meeting_id/users/:user_id/attendance' => 'attendances#destroy', :method => :DELETE, :as => :delete_meeting_attedance

  devise_for :users
  root :to => 'churches#index'
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :church_id, :weekly_meeting_id, 
                  :description, :end_time, :location, :name, :start_time, 
                  :attendance_count, :prophesy_count

  scope :after_time, lambda {|this_time| where("start_time > ?", this_time.to_s(:db)) }
  scope :before_time, lambda { |this_time| where("end_time < ?", this_time.to_s(:db)) }

  belongs_to :church
  
  def self.find_or_create_by_weekly_meeting(weekly_meeting, beginning_of_week)
    meeting_start_time = beginning_of_week.advance(:days => weekly_meeting.weekday-1, :hours => weekly_meeting.start_hour)
    meeting_end_time = beginning_of_week.advance(:days => weekly_meeting.weekday-1, :hours => weekly_meeting.end_hour)

    meeting = Meeting.where(:church_id => weekly_meeting.church_id, :name => weekly_meeting.name,
    :start_time => meeting_start_time, :end_time => meeting_end_time).first
    
    if meeting.nil?
      meeting = Meeting.create(:church_id => weekly_meeting.church_id, :name => weekly_meeting.name, :location => weekly_meeting.location,  
      :start_time => meeting_start_time, :end_time => meeting_end_time, :attendance_count => 0, :prophesy_count => 0)
    end
    meeting
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :load_church
  # GET /weekly_meetings
  # GET /weekly_meetings.json
  def load_church
    @church = Church.find(params[:church_id])
  end

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to weekly_calendar_url, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(meeting_params)
        format.html { redirect_to weekly_calendar_url, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  private

  # Use this method to whitelist the permissible parameters. Example:
  # params.require(:person).permit(:name, :age)
  # Also, you can specialize this method with per-user checking of permissible attributes.
  def meeting_params
    params.require(:meeting).permit(:church_id, :description, :end_time, :location, :name, :start_time)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.haml
= form_for [ :church, @meeting] do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :attendance_count
    = f.text_field :attendance_count
  .field
    = f.label :prophesy_count
    = f.text_field :prophesy_count
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', edit_church_meeting_path(@church, @meeting)
\|
= link_to 'Back', church_meetings_path(@church)

app/views/meetings/index.html.haml
%h1 Listing meetings

%table
  %tr
    %th Church
    %th Name
    %th Start time
    %th End time
    %th Location
    %th Description
    %th
    %th
    %th

  - @meetings.each do |meeting|
    %tr
      %td= meeting.church_id
      %td= meeting.name
      %td= meeting.start_time
      %td= meeting.end_time
      %td= meeting.location
      %td= meeting.description
      %td= link_to 'Show', meeting
      %td= link_to 'Edit', edit_meeting_path(meeting)
      %td= link_to 'Destroy', meeting, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', church_meetings_path(@church)

app/views/meetings/show.html.haml
%p#notice= notice

%p
  %b Church:
  = @meeting.church_id
%p
  %b Name:
  = @meeting.name
%p
  %b Start time:
  = @meeting.start_time
%p
  %b End time:
  = @meeting.end_time
%p
  %b Location:
  = @meeting.location
%p
  %b Description:
  = @meeting.description

= link_to 'Edit', edit_church_meeting_path(@church, @meeting)
\|
= link_to 'Back', church_meetings_path(@church)