config/routes.rb
GoodShepherd::Application.routes.draw do
  #comment
  resources :events
  resources :churches do
    get :members, :on => :member
    resources :weekly_meetings
    resources :meetings do
      resources :attendances, :only => [:create]
    end
    get 'upload_directory', :on => :member
    post 'upload_directory', :on => :member    
  end
  
  match '/weekly_calendar' => 'churches#calendar', :as => :weekly_calendar
  match '/weekly_calendar/meetings' => 'churches#calendar_meetings', :as => :weekly_calendar_meetings

  match '/meetings/:meeting_id/users/:user_id/attendance' => 'attendances#destroy', :method => :DELETE, :as => :delete_meeting_attedance

  devise_for :users
  root :to => 'churches#index'
end

app/models/weekly_meeting.rb
class WeeklyMeeting < ActiveRecord::Base
  attr_accessible :church_id, :description, :end_hour, :location, :name, :start_hour, :weekday  
  belongs_to :church
  has_many :meetings
  
  before_save :input_to_number
  
  validates_presence_of :name
  validates_inclusion_of :weekday, :in => 1..7
  validates_numericality_of :start_hour, :greater_than_or_equal_to => 0, :less_than => 24 
  validates_numericality_of :end_hour, :greater_than_or_equal_to => 0, :less_than => 24
  
  def input_to_number
    self.start_hour = self.start_hour.to_f
    self.end_hour = self.end_hour.to_f
    puts self.inspect       
  end  
end

app/controllers/weekly_meetings_controller.rb
class WeeklyMeetingsController < ApplicationController
  before_filter :load_church
  # GET /weekly_meetings
  # GET /weekly_meetings.json
  def load_church
    @church = Church.find(params[:church_id])
  end
  
  def index    
    @weekly_meetings = @church.weekly_meetings  
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weekly_meetings }
    end
  end

  # GET /weekly_meetings/1
  # GET /weekly_meetings/1.json
  def show
    @weekly_meeting = WeeklyMeeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weekly_meeting }
    end
  end

  # GET /weekly_meetings/new
  # GET /weekly_meetings/new.json
  def new
    @weekly_meeting = WeeklyMeeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weekly_meeting }
    end
  end

  # GET /weekly_meetings/1/edit
  def edit
    @weekly_meeting = WeeklyMeeting.find(params[:id])
  end

  # POST /weekly_meetings
  # POST /weekly_meetings.json
  def create
    @weekly_meeting = WeeklyMeeting.new(weekly_meeting_params)

    respond_to do |format|
      if @weekly_meeting.save
        format.html { redirect_to @weekly_meeting, notice: 'Weekly meeting was successfully created.' }
        format.json { render json: @weekly_meeting, status: :created, location: @weekly_meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @weekly_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_meetings/1
  # PATCH/PUT /weekly_meetings/1.json
  def update
    @weekly_meeting = WeeklyMeeting.find(params[:id])

    respond_to do |format|
      if @weekly_meeting.update_attributes(weekly_meeting_params)
        format.html { redirect_to @weekly_meeting, notice: 'Weekly meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weekly_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_meetings/1
  # DELETE /weekly_meetings/1.json
  def destroy
    @weekly_meeting = WeeklyMeeting.find(params[:id])
    @weekly_meeting.destroy

    respond_to do |format|
      format.html { redirect_to weekly_meetings_url }
      format.json { head :no_content }
    end
  end

  private

  # Use this method to whitelist the permissible parameters. Example:
  # params.require(:person).permit(:name, :age)
  # Also, you can specialize this method with per-user checking of permissible attributes.
  def weekly_meeting_params
    params.require(:weekly_meeting).permit(:church_id, :description, :end_time, :location, :name, :start_time, :weekday)
  end
end

app/helpers/weekly_meetings_helper.rb
module WeeklyMeetingsHelper
end

app/views/weekly_meetings/_form.html.haml
= form_for [ :church, @weekly_meeting] do |f|
  - if @weekly_meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weekly_meeting.errors.count, "error")} prohibited this weekly_meeting from being saved:"
      %ul
        - @weekly_meeting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_hour
    = f.number_field :start_hour
  .field
    = f.label :end_hour
    = f.number_field :end_hour
  .field
    = f.label :weekday
    = f.number_field :weekday
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/weekly_meetings/edit.html.haml
%h1 Editing weekly meeting

= render 'form'

= link_to 'Show', church_weekly_meeting_path(@church, @weekly_meeting)
\|
= link_to 'Back', church_weekly_meetings_path(@church)

app/views/weekly_meetings/index.html.haml
%h2 Weekly Meetings
%h4= @church.name
      
%table.table.table-bordered.table.table-striped
  %tr
    %th Name
    %th Start hour
    %th End hour
    %th Weekday
    %th Location
    %th Description
    %th
    %th
    %th

  - @weekly_meetings.each do |weekly_meeting|
    %tr
      %td= weekly_meeting.name
      %td= weekly_meeting.start_hour
      %td= weekly_meeting.end_hour
      %td= weekly_meeting.weekday
      %td= weekly_meeting.location
      %td= weekly_meeting.description
      %td= link_to 'Show', church_weekly_meeting_path(current_user.current_church, weekly_meeting)
      %td= link_to 'Edit', edit_church_weekly_meeting_path(current_user.current_church, weekly_meeting)
      %td= link_to 'Destroy', church_weekly_meeting_path(current_user.current_church, weekly_meeting), :method => :delete, :data => { :confirm => 'Are you sure?' }

.form-actions
  .btn.btn-primary= link_to 'Create New Meeting', new_church_weekly_meeting_path(current_user.current_church)

app/views/weekly_meetings/new.html.haml
%h1 New Weekly Meeting

= render 'form'

= link_to 'Back', church_weekly_meetings_path(@church)

app/views/weekly_meetings/show.html.haml
%p#notice= notice

%p
  %b Church:
  = @weekly_meeting.church_id
%p
  %b Name:
  = @weekly_meeting.name
%p
  %b Start hour:
  = @weekly_meeting.start_hour
%p
  %b End hour:
  = @weekly_meeting.end_hour
%p
  %b Weekday:
  = @weekly_meeting.weekday
%p
  %b Location:
  = @weekly_meeting.location
%p
  %b Description:
  = @weekly_meeting.description

= link_to 'Edit', edit_church_weekly_meeting_path(@church, @weekly_meeting)
\|
= link_to 'Back', church_weekly_meetings_path(@church)